### ISSUE TITLE
through hole of the power socket (NEB 21 R)

### ISSUE THREAD

**Issue by ChangQing-SH** [pyControl/hardware#2]
1. it's wrong, the through-hole doesn't match the pin of the socket.

2. no label text for the components.  and also no pin direction of IC

**Comment by ThomasAkam** [comment]
Hello ChangQuing,

Which board are you refering to?  

We have assembled all of the boards in the pyControl hardware repository so I do not think there is a problem with the design files.  The holes for the power socket are milled slots rather than drilled holes, so they are defined in a different gerber layer (.GML file) than the holes for most of the other components.  It is possible that when you got the PCBs fabricated they did not process the milling layer so the slots for the power socket were not cut.

**Comment by ChangQing-SH** [comment]
Hi，
Thanks for your reply.
![image](https://user-images.githubusercontent.com/48444988/96707797-ed455e80-13ca-11eb-8a8b-ad73514d9d94.png)
This is the breakout PCB I got

**Comment by ThomasAkam** [comment]
Hi ChangQuing,

Apolgies for the delay getting back to you.  I have now added gerber files to the hardware repository for all the PCBs, which should prevent problems like the one you ran into in future.  The lack of text labels for some components on your board was  also due to some of the layers in the board file not being included in gerbers.

Regarding the orientation of the resitor array, I have now added a mark to the board showing pin 1:
![image](https://user-images.githubusercontent.com/4661184/101058937-a2039b80-3585-11eb-80b6-efafebf50241.png)

Regarding desoldering the 0805 resistors on the pyboard, these are pull up resistors that pull some of the pins used as DIO on the behaviour ports up to 3.3v.  They are there on the pyboard so these pins can be used for I2C communication without external pullup resistors.  Normally it is no problem not to desolder these for use with pyControl, the only situation when it might cause an issue is if you were using the pins as inputs and the external device driving the pin had high output impedence so it could not overcome the influence of the pull up resistor.
